spring:
  cloud:
    gateway:
      routes:
        - id: monolithModule
          uri: lb://monolith
          predicates:
            - Path=/cart/**, /order/**

        - id: bffModule
          uri: lb://bff-service
          predicates:
            - Path=/product/**, /group/**, /groupVariant/**

        - id: securityModule
          uri: lb://security-service
          predicates:
            - Path=/security/**