spring:
  cloud:
    gateway:
      routes:
        - id: monolithModule
          uri: lb://monolith
          predicates:
            - Path=/cart/**, /order/**

        - id: bfftModule
          uri: lb://bff-service
          predicates:
            - Path=/product/**, /group/**, /groupVariant/**