eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    initialStatus: STARTING

spring:
  datasource:
    url: jdbc:mysql://localhost:3310/ecommerce
    driver: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        show_sql: false
        cache:
          use_query_cache: false
          use_second_level_cache: false
  cloud:
    config:
      allowOverride: true

jwt:
  header: Authentication
  expires_in: 86400
  secret: sgd34bwfAbfSBPpe0r8gwbg


