eureka:
  instance:
    initialStatus: STARTING

spring:
  datasource:
    url: jdbc:mysql://localhost:3310/product

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 60000
        requestVolumeThreshold: 3

recommendation:
  default: 7, 8, 11